# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - dev

pr:
  branches:
    include:
    - master


pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) -o $(Build.BinariesDirectory)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test Test/LinkCollectionApp.Test.csproj --logger trx
  displayName: 'dotnet test'

- task: Npm@1
  displayName: npm ci
  inputs:
    command: 'ci'
    workingDir: 'Main/ClientApp'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(Build.ArtifactStagingDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(8d3cf290-9c6a-436e-b20d-8ca855b60e58)'
    appType: 'webAppLinux'
    appName: 'linkcollectionapp'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'DOTNETCORE|LTS'