# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    exclude:
    - master

pr:
  branches:
    include:
    - master


pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'



steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.100'
  inputs:
    packageType: sdk
    version: 3.1.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: dotnet build $(buildConfiguration)
  inputs:
    command: 'build'
    projects: 'Main/LinkCollectionApp.csproj'
    arguments: '--configuration $(buildConfiguration) -o $(Build.BinariesDirectory)'

# - task: DotNetCoreCLI@2
#   displayName: dotnet test
#   inputs:
#     command: 'test'
#     projects: 'Test/LinkCollectionApp.Test.csproj'

# - task: Npm@1
#   displayName: npm ci
#   inputs:
#     command: 'ci'
#     workingDir: 'Main/ClientApp'

# - task: Npm@1
#   displayName: npm test
#   inputs:
#     command: 'custom'
#     workingDir: 'Main/ClientApp'
#     customCommand: 'test'

# - task: DotNetCoreCLI@2
#   displayName: dotnet publish
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     arguments: '-o $(Build.ArtifactStagingDirectory)'

# - task: AzureWebApp@1
#   displayName: Publish to Azure
#   inputs:
#     azureSubscription: 'Azure for Students(8d3cf290-9c6a-436e-b20d-8ca855b60e58)'
#     appType: 'webAppLinux'
#     appName: 'LinkCollectionApp'
#     package: '$(Build.ArtifactStagingDirectory)/*.zip'
#     runtimeStack: 'DOTNETCORE|LTS'

- script: dotnet tool install --global dotnet-ef
  displayName: 'dotnet install ef'

# - task: DotNetCoreCLI@2
#   displayName: install ef core
#   inputs:
#     command: 'custom'
#     custom: 'tool install --global dotnet-ef'

- script: dotnet ef migrations script --project Main\LinkCollectionApp.csproj --output $(Build.ArtifactStagingDirectory)\sql\migrations.sql -i
# - task: DotNetCoreCLI@2
#   displayName: Generate migration script
#   inputs:
#     command: 'custom'
#     custom: 'ef migrations script'
#     arguments: '--output $(Build.ArtifactStagingDirectory)\sql\migrations.sql -i'

- task: SqlAzureDacpacDeployment@1
  displayName: database update
  inputs:
    azureSubscription: 'Azure for Students(8d3cf290-9c6a-436e-b20d-8ca855b60e58)'
    AuthenticationType: 'connectionString'
    ConnectionString: '$(ApplicationDbContextConnection)'
    deployType: 'SqlTask'
    SqlFile: '$(Build.ArtifactStagingDirectory)\sql\migrations.sql'
    IpDetectionMethod: 'AutoDetect' 

