# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - master

variables:
  buildConfiguration: 'Release'
  # CI: true


jobs:
- job: build
  displayName: Build & Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1.100'
    inputs:
      packageType: sdk
      version: 3.1.100
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: dotnet install ef core
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global dotnet-ef'

  - task: Npm@1
    displayName: npm ci
    inputs:
      command: 'ci'
      workingDir: 'Main/ClientApp'

  # - task: DotNetCoreCLI@2
  #   displayName: dotnet build $(buildConfiguration)
  #   inputs:
  #     command: 'build'
  #     projects: 'Main/LinkCollectionApp.csproj'
  #     arguments: '--configuration $(buildConfiguration) -o $(Build.BinariesDirectory)'

  # - task: DotNetCoreCLI@2
  #   displayName: dotnet test
  #   inputs:
  #     command: 'test'
  #     projects: 'Test/LinkCollectionApp.Test.csproj'

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    #TODO: Change to master
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev')) 
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '-o $(Build.ArtifactStagingDirectory)'
  
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: WebApp
  

  # - task: Npm@1
  #   displayName: npm test
  #   inputs:
  #     command: 'custom'
  #     workingDir: 'Main/ClientApp'
  #     customCommand: 'test'

- deployment: deploy
  displayName: Azure Deploy
  dependsOn: build
  environment: LinkCollectionApp-dev
  pool:
    vm-image: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: WebApp

        - task: AzureWebApp@1
          displayName: Publish to Azure
          inputs:
            azureSubscription: 'Azure for Students(8d3cf290-9c6a-436e-b20d-8ca855b60e58)'
            appType: 'webAppLinux'
            appName: 'LinkCollectionApp'
            package: '$(Pipeline.Workspace)/WebApp/*.zip'
            runtimeStack: 'DOTNETCORE|Latest'

        # - script: dotnet ef migrations script --project Main/LinkCollectionApp.csproj --output $(Build.ArtifactStagingDirectory)\sql\migrations.sql -i
        - task: DotNetCoreCLI@2
          displayName: dotnet ef migrations script
          inputs:
            command: 'custom'
            custom: 'ef'
            arguments: 'migrations script--output $(Build.ArtifactStagingDirectory)\sql\migrations.sql -i'

        - task: SqlAzureDacpacDeployment@1
          displayName: Update Azure database
          inputs:
            azureSubscription: 'Azure for Students(8d3cf290-9c6a-436e-b20d-8ca855b60e58)'
            AuthenticationType: 'connectionString'
            ConnectionString: '$(ApplicationDbContextConnection)'
            deployType: 'SqlTask'
            SqlFile: '$(Build.ArtifactStagingDirectory)\sql\migrations.sql'
            IpDetectionMethod: 'AutoDetect' 

